[package]
name = "locus_engine"
version = "0.1.0"
authors = ["Christofer Nolander <christofer.nolander@gmail.com>"]

[dependencies]

gfx = "0.16.1"
glutin = "0.10.1"
gfx_window_glutin = "0.18.0"

time = "0.1"