[package]
name = "crank"
version = "0.1.0"
authors = ["Christofer Nolander <christofer.nolander@gmail.com>"]


[lib]
name = "crank"
path = "src/lib.rs"

[[bin]]
name = "crank_dev"
path = "dev/src/main.rs"


[dependencies]

gl = "0.7.0"
