


/// A window that is shown to the user
struct Window {

}

/// Frontend for the game to use when making updates to the window
pub struct WindowHandle {

}


/// Handles events generated by a window
pub trait WindowEventHandler {
    /// Called when the window changes size
    ///
    /// # Arguments
    ///
    /// * 'width' - The new width of the window
    /// * 'height' - The new height of the window
    fn size_changed(&mut self, width: usize, height: usize);


    /// Called when a key is pressed within the window
    ///
    /// # Arguments
    ///
    /// * 'key' - The key that was pressed
    fn key_pressed(&mut self, key: KeyCode);

}



impl Window {
    // TODO: Implement 'new'

    /// Creates a new window
    pub fn new() {
    }
}
